### ISSUE TITLE
Request for release posters of ROMs in telegram channels 

### ISSUE THREAD

**Issue by ArberTu474** [Evolution-X-AOSP/vendor_evolution#37]
I have seen that the developers use different posters for rom releases on their Telegram channels. This doesn't like professional in my opinion, so I made some posters for some devices to illustrate my idea.

Each device is going to have it's own corresponding color (matching Google's Material You design language) and a simplified version of the front screen of the device.
These are some examples:
####
![Mi 11](https://user-images.githubusercontent.com/88089607/198851068-c9ea4880-dc9a-41b5-b7a5-8457e53b7c43.png)
###
![OnePlus 7 Pro](https://user-images.githubusercontent.com/88089607/198851080-2bac8eec-f5f0-4838-bed3-286c478ed4f2.png)
####
![Poco X4 Pro 5G](https://user-images.githubusercontent.com/88089607/198851085-ec016ce1-4f66-42ca-bd0e-7f125f723632.png)
####
![Redmi 7a](https://user-images.githubusercontent.com/88089607/198851095-8cda0292-dbfb-4d04-8749-6a7b889c4723.png)

**Comment by AnierinBliss** [comment]
Looks pretty nice to me. Feel free to contact me on telegam @ anierin_bliss
